name: Test PR

on: pull_request

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'
          cache: maven

      - name: Run unit tests
        run: ./mvnw test -DskipTests=false

#      - name: Secret Scanning
#        uses: trufflesecurity/trufflehog@main
#        with:
#          base: main
#          # extra_args: --results=verified,unknown

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs' # filesystem mode
          scan-ref: '.'
          format: 'table'
          exit-code: '1' # fail pipeline on detected error
          scanners: 'vuln,misconfig' # use these two scanner categories
          severity: 'CRITICAL,HIGH,MEDIUM' # skip UNKNOWN and LOW
          skip-dirs: '.devcontainer' # ignore this directory
